# Generated by Django 5.0.6 on 2024-06-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_items_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_exp_date',
            field=models.DateField(blank=True),
        ),
    ]
