# Generated by Django 5.0.6 on 2024-06-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_items_item_exp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_pic',
            field=models.ImageField(blank=True, upload_to='Share/Cycle/image/items'),
        ),
    ]
