# Generated by Django 5.0.6 on 2024-06-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_items_item_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='item_id',
        ),
        migrations.AlterField(
            model_name='items',
            name='item_pic',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_profile',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile'),
        ),
    ]
