# Generated by Django 5.0.6 on 2024-06-16 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_items_item_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='user',
        ),
    ]
