# Generated by Django 5.0.6 on 2024-06-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_items_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_category',
            field=models.CharField(choices=[('Food', 'Food'), ('Clothing', 'Clothing'), ('Books', 'Books'), ('Other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_description',
            field=models.CharField(max_length=500),
        ),
    ]
